apiVersion: v2
name: rag
description: A Helm chart for Kubernetes
type: application
version: 0.2.22
appVersion: "0.2.22"

dependencies:
  - name: pgvector
    version: 0.1.0
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: pgvector.enabled
  - name: minio
    version: 0.1.0
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: minio.enabled
  - name: llm-service
    version: 0.1.0
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: llm-service.enabled
  - name: configure-pipeline
    version: 0.1.0
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: configure-pipeline.enabled
  - name: ingestion-pipeline
    version: 0.5.1
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: ingestion-pipeline.enabled
  - name: llama-stack
    version: 0.5.0
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: llama-stack.enabled
  - name: mcp-servers
    version: 0.1.0
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: mcp-servers.enabled
