name: ansible-lint
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ansible-lint
        run: |
          pip install --upgrade pip
          pip install "ansible-core>=2.12,<2.18" "ansible-lint>=6.0"

      - name: Run ansible-lint
        run: ansible-lint
